verify_signatures: false
PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail

  BundlerAudit:
    enabled: true
    command: [ 'bundle', 'audit', 'check', '--update' ]
    on_warn: fail

  Brakeman:
    enabled: true
    command: [ 'brakeman' ]
    on_warn: fail

  RSpec:
    enabled: true
    command: [ 'bundle', 'exec', 'rspec' ]
    on_warn: fail