AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'test/dummy/db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/dummy/db/schema.rb'
    - 'spec/requests/activejob_web/jobs_controller_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/20231024051840_create_jobs.rb'
